target = "MakeLangId"

files = Split("""
	MakeLangId.cpp
""")

res = Split("""
	resource.rc
""")

resources = Split("""
	MakeLangId.xml
""")

libs = Split("""
	kernel32
	user32
	comctl32
""")

Import('env WriteResourceVersion')
WriteResourceVersion('resource.rc', env['VER_MAJOR'], env['VER_MINOR'], env['VER_REVISION'], env['VER_BUILD'])

Import('BuildUtil')

BuildUtil(target, files, libs, res = res, resources = resources, entry = 'NSISWinMainNOCRT', nodeflib = True)

