target = 'makensisw'

files = Split("""
	makensisw.cpp
	toolbar.cpp
	utils.cpp
	version.cpp
	update.cpp
	lookup.cpp
	wndspy.cpp
""")

res = Split("""
	resource.rc
""")

resources = Split("""
	icon.ico
	assoc_nsi.ico
	assoc_nsh.ico
	makensisw.xml
	toolbar.bmp
	toolbar16n24.bmp
	toolbar16d24.bmp
	toolbar16h24.bmp
	toolbar24n24.bmp
	toolbar24d24.bmp
	toolbar24h24.bmp
	toolbar32n24.bmp
	toolbar32d24.bmp
	toolbar32h24.bmp
""")

libs = Split("""
	advapi32
	user32
	gdi32
	msimg32
	shell32
	shlwapi
	comdlg32
	comctl32
	wininet
	winmm
	kernel32
	ole32
""")

docs = Split("""
	License.txt
	Readme.txt
""")

Import('env WriteResourceVersion')
WriteResourceVersion('resource.rc', env['VER_MAJOR'], env['VER_MINOR'], env['VER_REVISION'], env['VER_BUILD'])

Import('BuildUtil')

BuildUtil(
	target,
	files,
	libs,
	res = res,
	resources = resources,
	entry = None,
	defines = ['RELEASE=2.4.1'],
	docs = docs,
	root_util = True
)
